### ISSUE TITLE
Dataset google drive link is broken

### ISSUE THREAD

**Issue by bamsumit** [Durant35/PilotNet#1]
Hi, thanks for your repo. The dataset link seems to be broken recently. Can you please help fix it? Thanks in advance.

**Comment by Durant35** [comment]
您发送的邮件已经收到。。。

**Comment by FourierX9** [comment]
Hi! I have the same problem. I cannot find the dataset file. It would be nice if the problem could be fixed! Thanks

**Comment by bamsumit** [comment]
@FourierX9 here is the link from the parent fork: https://github.com/SullyChen/driving-datasets

**Comment by Durant35** [comment]
> @FourierX9 here is the link from the parent fork: https://github.com/SullyChen/driving-datasets

Yes, many thanks! And this is the link that I used, https://drive.google.com/file/d/1Ue4XohCOV5YXy57S_5tDfCVqzLr101M7/view, I will update the README and also backup the dataset.
